remote_theme: poole/hyde
theme: jekyll-theme-hyde
title: LangTrans
description: Customize Programming Language
repository: "LangTrans/LangTrans"
footer-links:
  github: langtrans
plugins:
  - jekyll-seo-tag
google_analytics: UA-153183472-2
font:
  enable: true
  posts:
    size: 21
  headings:
      size: 30
highlighter: redcarpet
