theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout
title: LangTrans
description: Customize Programming Language
repository: "LangTrans/LangTrans"
footer-links:
  github: langtrans
plugins:
  - jekyll-seo-tag
google_analytics: UA-153183472-2
