theme: jekyll-theme-cayman
title: LangTrans
description: Customize Programming Languages
repository: "LangTrans/LangTrans"
footer-links:
  github: langtrans
plugins:
  - jekyll-seo-tag
google_analytics: UA-153183472-2
