theme: jekyll-theme-primer
title: LangTrans
description: Customize Programming Language
repository: "LangTrans/LangTrans"
footer-links:
  github: langtrans
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
google_analytics: UA-153183472-2
kramdown:
  input: GFM
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    css_class: 'highlight'
