remote_theme: poole/hyde
title: LangTrans
description: Customize Programming Language
repository: "LangTrans/LangTrans"
footer-links:
  github: langtrans
plugins:
  - jekyll-seo-tag
google_analytics: UA-153183472-2
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
